---
title: "MAD_TP1"
author: "You ZUO"
date: "2019/9/16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

##Exo1
```{r}
1-pnorm(120,mean = 100,sd = 15)
pnorm(100,mean = 100,sd = 15)


QI.sup120 <- function(x){
  ifelse(x>120,dnorm(x,mean = 100, sd = 15), NA)
}

library(ggplot2)
ggplot(data.frame(x=c(20,180)),aes(x)) +
  stat_function(fun = dnorm, args = list(mean=100,sd=15)) +
  stat_function(fun = QI.sup120, geom = "area", fill = "coral", alpha = 0.3) +
  geom_vline(xintercept = 120)


QI.inf100 <- function(x){
  ifelse(x<100,dnorm(x,mean = 100,sd = 15), NA)
}
ggplot(data.frame(x=c(20,180)),aes(x)) +
  stat_function(fun = dnorm, args = list(mean=100,sd=15)) +
  stat_function(fun = QI.inf100, geom = "area", fill = "coral", alpha = 0.3) +
  geom_vline(xintercept = 100)

curve(dnorm(x,mean = 100,sd = 15),20,180)
```

##Exo2
$$\hat{\sigma_{ML}}=\frac{1}{n}\sum_{i=1}^n(x_i-\bar{x})^2$$
with $\hat{x}=\frac{1}{n}\sum x_i$
```{r}
n <- seq(from = 100, to = 100000, by = 500)
varx <- sapply(n,function(m){
  x <- rnorm(m,mean = 100,sd = 15)
  var(x)
})
plot(sqrt(varx))
abline(h = 15, col = "red", lwd = 2)

n <- 10
x <- rnorm(n = 10, mean = 100, sd = 15)
sigma2ML <- mean((x-mean(x))^2)
sigma2stat <- n/(n-1)*sigma2ML
var(x)
sigma2ML
sigma2stat
```

##Exo3
```{r}
data("iris")
str(iris)
help("iris")
summary(iris)
plot(iris)
pairs(iris[,1:4], col = iris$Species)
```

```{r warning=FALSE}
library(tidyverse)
parameters <-
  as.tibble(iris) %>%
  select(-"Species") %>%
  gather(factor_key = TRUE) %>%
  group_by(key) %>%
  summarise(mean = mean(value), sd = sd(value)) %>%
  mutate(min=mean - 2*sd, max = mean + 2*sd)

flower.outliers <- (apply(t((t(iris[,1:4]) < parameters$min) + (t(iris[,1:4]) > parameters$max)),1,sum)>0)
ggplot(iris, aes(x=Sepal.Length,y=Sepal.Width)) +
  geom_point(colour = as.numeric(iris$Species), size = flower.outliers*2+1)
```

### exo4
```{r}
library(mvtnorm)
library(MASS)
sigma = matrix(nrow = 2, ncol = 2, data = c(2,1,1,0.75))
mu = matrix(c(0,0),2,1) 

X <- mvrnorm(n = 1000, mu = mu, Sigma = sigma)
plot(X)

Q <- qchisq(p = seq(0.05,0.95,by = 0.01), df = 2)
x <- seq(-4,4,length=100)
y <- seq(-4,4,length=100)
sigmainv <- solve(sigma)
a <- sigmainv[1,1]
b <- sigmainv[2,2]
c <- sigmainv[1,2]
z <- outer(x,y,function(x,y) (a*x^2+b*y^2+2*c*x*y))
image(x,y,z)
contour(x,y,z,col = "blue4", levels = Q, labels = seq(0.05,0.95,0.1),add=T)
persp(x,y,1/(2*pi)*det(sigmainv)^(-1/2)*exp(-0.5*z),col = "cornflowerblue",theta = 5, phi = 10, zlab = "f(x)")

```

$$logf(x_1,x_2)=-\frac{1}{2}(x_1,x_2)\Sigma^{-1}(x_1,x_2)^t$$
